#Modelo con un solo bien, gobierno y producción

En este modelo la cantidad del bien disponible en la economía se produce por lo que $y_s = A_sf(k_s)$ para cada $s \geq t$ y donde $A_s$ es la productividad en el periodo $s$ y $k_s$ es la cantidad de capital en la economía en el periodo $s$. Se asume que no hay depreciación del capital. Además la inversión para cada periodo $s \geq t$ está dada por $i_s = k_{s+1} - k_s$

## Problema de optimización

El agente representativo busca

$$
\max_{c_s,b_{s+1}, k_{s+1}, s \geq t} \{ \sum_{s \geq t} \beta^{s-t}(\ln(c_s) + v(g_s)):c_s + b_{s+1} + \tau_s + k_{s+1}-k_s = A_sf(k_s) + (1+r_{s-1})b_s, s\geq t\}
$$
EL gobierno debe cumplir su restricción presupuestal como lo hemos visto en secciones anteriores. En este problema están dados $\{y_s, r_{s-1}\}_{s\geq t}$, $b_t$, $d_t$ y $k_t$. Introduciendo la restricción presupuestal del gobierno en la del agente representativo y la inversión se obtiene que,

$$
\begin{equation}
c_s + g_s + b_{s+1} - d_{s+1} + i_s = A_sf(k_s) + (1+r_{s-1})(b_s - d_s)
(\#eq:rpcapgob)
\end{equation}
$$
Así, la balanza comercial está dada por,

$$
T_s = A_s f(k_s) - c_s - g_s - i_s
$$
En tanto que la cuenta corriente está dada por,

$$
CA_s = A_sf(k_s) - c_s - g_s -i_s + r_{s-1}(b_s - d_s) = T_s + r_{s-1}(b_s - d_s)
$$


## Condiciones de primer orden

Las condciones de optimalidad de este problema están dadas por

$$
c_{s+1} = \beta(1+r_s)c_s
$$

Para cada $s \geq t$. Y además,

$$
A_{s+1}f'(k_{s+1}) = r_s
$$

##Restricción presupuestal

Iterando la restricción presupuestal \@ref(eq:rpcapgob) a partir de $s$ se obtiene que, en el óptimo, para cada $s \geq t$,

$$
\sum_{j \geq s} \Delta_j T_j = -(1+ r_{s-1})(b_s-d_s)
$$
O bien,

$$
\sum_{j \geq s} \Delta_j c_j = (1 + r_{s-1})(b_s - d_s) + \sum_{j \geq s}\Delta_j(A_j f(k_j) -g_j-i_j) 
$$

*En particular* para el presente se verifica que,

$$
\sum_{s \geq t} \Delta_s c_s = (1 + r_{t-1})(b_t - d_t) + \sum_{s \geq t} \Delta_s (A_sf(k_s) - g_s - i_s)
$$
##Solución

A partir de la ecuación de euler se verifica para cada $s \geq t$ y cada $j \geq s$ lo siguiente,

$$
\Delta_j c_j = \beta^{j-s}\Delta_sc_s
$$
Por lo tanto, para cada $s \geq t$ el consumo está dado por,

$$
c_s = (1-\beta)(1 + r_{s-1})b_s + \widehat{A_sf(k_s)} - \hat{g_s} - \hat{i_s}
$$

El lado derecho de la ecuación anterior es conocida pues a partir de la condición de eficiencia del capital puede conocerce la senda de equilibrio.

##Supuestos habituales

Si $r_{s-1} = r^*$ para cada $s \geq t$ y $\beta(1 + r^*) = 1$ entonces, por la condición de euler, el consumo es el mismo en todos los periodos y 

$$
c = c_s = r^*(b_s - d_s) + \widehat{A_sf(k_s)} - \hat{g_s} - \hat{i_s}
$$

En este caso, la cuenta corriente está dada por,

$$
CA_s = (A_sf(k_s) - \widehat{A_sf(k_s)}) - (g_s - \hat{g_s})- (i_s - \hat{i_s})
$$

##Ejemplo

Supongamos que $r_{s-1} = r^*$ para cada $s \geq t$, $\beta(1 + r^*) = 1$, $b_t = 0$, $f(k_s) = k_s^{\alpha}$, $g_s = 0$, $A_s = A$ para cada $s \geq t$. Además se supone que el capital inicial cumple con la condición de eficiencia del capital en $t$; es decir, $\alpha Ak_t^{\alpha-1} = r^*$. Como $A$ no cambia en el tiempo, el capital es el mismo para todos los periodos pues la condición de eficiencia señala que $\alpha Ak_{s+1}^{\alpha -1} = r^*$ para $s \geq t+1$. Por lo tanto, $k = k_{s}$ para cada $s \geq t$. Con lo anterior, $i_s = 0$ para cada $s \geq t$ y $A_s f(k_s) = Ak^{\alpha}$ de aquí se verifica que,

$$
c = c_t = A k_t ^{\alpha}
$$

### Choque en la productividad

Apartir de las condiciones anteriores, suponemos un choque positivo en la productividad a partir del periodo $t$ durante $h$ periodos. Formalmente, $A_s = \lambda^{1-\alpha}A$ con $\lambda > 1$ si $t \leq s \leq t+h-1$ y $A_s = A$ si $s \geq t+h$. Además suponemos que el capital inicial cumple con la condición de eficiencia del capital en asuencia de choque, es decir, $\alpha Ak_t^{\alpha-1} = r^*$. Definimos $k_0 = k_t$. Luego, $k_s = k_0$ para $s \geq t+h$ y $k_s = k_1$ para $t \leq s \leq t+h-1$ donde $\alpha \lambda^{1-\alpha}Ak_1^{\alpha-1}$. Luego,

$$
\frac{\alpha Ak_0^{\alpha-1}}{\alpha \lambda^{1-\alpha}Ak_1^{\alpha-1}} = 1
$$

Así,a partir de lo anterior,

$$
(\lambda k_0)^{\alpha-1} = k_1^{\alpha-1}
$$
Por lo que, $k_1 = \lambda k_0$. A partir de esto tenemos tres niveles de producción. Si $s \geq t+h$ entonces,

$$
y_s = Ak_0^{\alpha} = y_0
$$

Por otro lado, si $t+1 \leq s \leq t+h-1$ entonces 

$$
y_s = \lambda^{1-\alpha}Ak_1^\alpha = \lambda Ak_0^{\alpha} = \lambda y_0 = y_1
$$

Por último, $y_t = \lambda^{1-\alpha}y_0$. Con el valor de la producción, tenemos que,

$$
\begin{align}
\hat{y_t} &= (1-\beta)\sum_{s\geq t}\beta^{s-t} y_s \\
&=(1-\beta)\left(\lambda^{1-\alpha}y_0 + \sum_{s = t+1}^{t+h-1}\beta^{s-t}\lambda y_0 + \sum_{s\geq t+h}\beta^{s-t}y_0 \right) \\
&= (1-\beta)\left(\lambda^{1-\alpha}y_0 + \frac{\beta(1-\beta^{h})\lambda y_0}{1-\beta} + \frac{\beta^h y_0}{1-\beta} \right) \\
&= (1-\beta)\lambda^{1-\alpha}y_0 + \beta(1-\beta^{h-1})\lambda y_0 + \beta^h y_0
\end{align}
$$

Asimismo, se verifica para la inversión que $i_t = k_1 - k_0 = (\lambda-1)k_0$, $i_s = k_{s+1} - k_s = 0$ para $t + 1 \leq s \leq t+h-2$, $i_s = k_{s+1}-k_s = k_0 - k_1 = (1-\lambda)k_0$ si $s = t+h-1$ y por último, $i_s = 0$ en otro caso. Así,

$$
\begin{align}
\hat{i_t} &= (1-\beta) \sum_{s\geq t} \beta^{s-t} i_s \\
&= (1-\beta)\left(i_t + \sum_{s = t+1}^{t+h-2}\beta^{s-t} i_s + \beta^{(t+h-1)-t}i_{t+h-1} + \sum_{s \geq t+h} \beta^{s-t} i_s \right) \\
&= (1-\beta)((\lambda-1)k_0 + \beta^{h-1}(1-\lambda)k_0) \\
&= (1-\beta)(1-\beta^{h-1})(\lambda - 1)k_0
\end{align}
$$
Por lo tanto, el consumo cuando el choque permanece $h$ periodos, denotado por $c_h$, está dado por,

$$
\begin{align}
c_h &= c_t \\
& = \hat{y_t} - \hat{i_t} \\
&= (1-\beta)\lambda^{1-\alpha}y_0 + \beta(1-\beta^{h-1})\lambda y_0 + \beta^h y_0 - (1-\beta)(1-\beta^{h-1})(\lambda - 1)k_0 
\end{align}
$$
Definamos $c_1$ como el consumo cuando el choque permanece un solo periodo, es decir $h = 1$. Luego,

$$
\begin{align}
c_1 &= (1-\beta)\lambda^{1-\alpha}y_0 + \beta(1-\beta^0)\lambda y_0 + \beta y_0 - (1-\beta)(1-\beta^{0})(\lambda - 1)k_0  \\
&= (1-\beta)\lambda^{1-\alpha} y_0 + \beta y_0
\end{align}
$$

Definamos, por otro lado, $c_p$ como el consumo cuando el choque es permanente, es decir $h \rightarrow \infty$. Luego, 

$$
\begin{align}
c_p &= \lim_{h \rightarrow \infty}  (1-\beta)\lambda^{1-\alpha}y_0 + \beta(1-\beta^{h-1})\lambda y_0 + \beta^h y_0 - (1-\beta)(1-\beta^{h-1})(\lambda - 1)k_0 \\
&= (1-\beta)\lambda^{1-\alpha}y_0 + \beta\lambda y_0 - (1-\beta)(\lambda - 1)k_0
\end{align}
$$
Por lo tanto, se verifica que

$$0o, _.nh cx
c_h = (1-\beta^{h-1})c_p + \beta^{h-1}c_1
$$

### Términos de intercambio

Ahora introducimoes los términos de intercambio $\{\Omega_s\}_{s\geq t}$. En este caso el producto en cada periodo está determinado por $\Omega_s A_s f(k_s)$, por lo que la solución es similar a la anterior. Si suponemos que $A_s = 1$ para cada $s \ geq t$ y que hay un choque positivo en los términos de intercammbio, es decir, $\Omega_s = \Omega$ si $s \leq t+1$, $s \geq t+h$ y $\Omega_s = \lambda^{1-\alpha}\Omega$ si $t \leq s \leq t+h-1$. En este caso, el choque es exactamente el mismo que en el caso anterior.

### Senda de crecimiento balanceado

Supongamos que la productividad crece a tasa constante, esto es 

$$
\frac{A_{s+1}}{A_s} = 1 + \hat{A}
$$

Para cada $s \geq t$. Además supongamos que la condición inicial del capital satisface la condición de optimalidad del capital; es decir, $\alpha A_t k_t^{\alpha-1} = r^*$. Este supuesto una implicación fundamental: el capital y la producción crecen a la misma tasa constante. Para verlo, recordemos que para cada $s \geq t+1$ se verifica que en el óptimo, $\alpha A_sk_s^{\alpha-1} = r^*$. A partir del supuesto de la condición inicial del capital, se cumple que para cada $s \geq t$,

$$
\frac{\alpha A_s k_s^{\alpha-1}}{\alpha A_{s+1} k_{s+1}^{\alpha-1}} = 1
$$

Por lo que, 

$$
\frac{k_{s+1}}{k_s} = (1 + \hat{A})^{\frac{1}{1-\alpha}} = 1 + \hat{y}
$$

La producción por otro lado,

$$
\frac{A_{s+1}k_{s+1}^{\alpha}}{A_s k_{s}^{\alpha}} = (1 + \hat{A})^{\frac{1}{1-\alpha}} = 1 + \hat{y}
$$

Lo anterior no es un supuesto del modelo sino un resultado de que la productivdad crezca a una tasa constante. Por otro lado, supongamos que $1+ r_{s-1} = 1+r^* = \beta^{-1}(1+ \hat{y})$ para cada $s \geq t$. En este caso, a partir de la ecuación de euler se verifica que $c_{s+1} = (1+\hat{y})c_s$ para cada $s \geq t$; es decir, el consumo crece a la misma tasa constante que el producto y el capital. Por tanto, para cualquier $s \geq t$,

$$
c_s = (1 + \hat{y})^{s-t}c_t
$$
Del mismo modo, para cada $s \geq t$

$$
y_s = (1 + \hat{y})^{s-t}y_t
$$

Y

$$
i_s = k_{s+1} - k_s = (1+\hat{y})k_s-k_s = (1+\hat{y})^{s-t}\hat{y}k_t = (1+\hat{y})^{s-t}i_t 
$$

Por lo tanto, para cada $s \geq t$,

$$
y_s - i_s = (1 + \hat{y})^{s-t}(y_t-i_t)
$$

Utilizando la ecuación anterior y que $\frac{1+\hat{y}}{1+r^*} = \beta$ se tiene que,

$$
\begin{align}
\hat{y_t} -\hat{i_t} &= (1-\beta)\sum_{s \geq t} \left(\frac{1}{1+r^*}\right)^{s-t}(y_s - i_s) \\
&= (1-\beta)(y_t - i_t)\sum_{s\geq t} \left(\frac{1 + \hat{y}}{1+r^*}\right)^{s-t} \\
&= (1-\beta)(y_t - i_t)\sum_{s\geq t}\beta^{s-t} \\
&= y_t - i_t
\end{align}
$$

Por lo tanto, 

$$
\begin{align}
c_t &= (1-\beta)(1+r^*)b_t + y_t - i_t\\
&=(r^*-\hat{y})b_t + y_t - i_t
\end{align}
$$

La balanza comercial está dada por,

$$
T_s = y_s - c_s - i_s = (1+\hat{y})^{s-t}(y_t-c_t-i_t) = (1+\hat{y})^{s-t}T_t
$$

Con 

$$
T_t = y_t-c_t-i_t = y_t - i_t - (r^*-\hat{y})b_t - (y_t - i_t) = -(r^*-\hat{y})b_t
$$

La cuenta corriente está dada por,

$$
CA_t = T_t + r^*b_t =  -(r^*-\hat{y})b_t + r^* b_t = \hat{y}b_t
$$

Como además $CA_t = b_{t+1} - b_t = \hat{y} b_t$ entonces $b_{s+1} = (1+\hat{y})b_s$ para cada $s \geq t$. De donde se obtiene que 

$$
CA_s = b_{s+1} - b_s = \hat{y}b_s = (1+\hat{y})^{s-t}\hat{y}b_t = (1+\hat{y})^{s-t}CA_t
$$

En particular,

$$
\frac{CA_s}{y_s} = \hat{y} \frac{b_t}{y_t}
$$

#### Depreciación del capital

A partir de las condciones anteriores, supongamos ahora que el capital sufre un choque negativo e inesperado en $t$. Formalmente, $i_s =(\theta + \hat{y})k_s$ si $s = t$ con $\theta \in (0,1)$ y $i_s = (1 + \hat{y})k_s$ para $s \geq t+1$. 